#ifdef DEBUG
C_FLAGS = -c -g -fpic -Wimplicit
#else
C_FLAGS = -c -fpic -Wimplicit
#endif

sockets.lsx: sockets.o asock.plm
	$(CC) -shared -o asock.lsx sockets.o
	cp asock.lsx $(AMZI_DEV_DIR)/lib/
	cp asock.plm $(AMZI_DEV_DIR)/abin/

sockets.o: sockets.c
	$(CC) -I$(AMZI_DEV_DIR)/include $(C_FLAGS) -o sockets.o sockets.c

asock.plm: asock.pro
	acmp asock

clean:
	rm *.o
	rm *.plm

