#debug
#C_FLAGS = -g
#release
C_FLAGS = -O6

CC = gcc

all: acgi

acgi: amzicgi.c amzisub.c $(AMZI_DEV_DIR)/lib/libamzi.so
	$(CC) -I$(AMZI_DEV_DIR)/include -L$(AMZI_DEV_DIR)/lib $(C_FLAGS) -o $(AMZI_DEV_DIR)/lsapis/cgi/acgi \
	   amzicgi.c amzisub.c -lamzi -lm -lstdc++
	acmp acgi
	cp acgi.plm $(AMZI_DEV_DIR)/abin/acgi.plm

clean:
	-rm *.o

