C_FLAGS = -O6

CC = gcc

all: petscb pets.xpl

petscb: petscb.cpp
	$(CC) -I$(AMZI_DIR)/include -L$(AMZI_DIR)/lib $(C_FLAGS) -lamzi -lm -lstdc++ -o petscb petscb.cpp

pets.xpl: pets.pro
	acmp pets
	alnk pets pets
